#
# Configure getdns_query to listen on localhost port 53, and operate as a stub resolver 
# to a remote authenticated TLS upstream
#
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
- GETDNS_TRANSPORT_TLS
upstream_recursive_servers:
- address_data: 185.49.141.38
  tls_auth_name: "getdnsapi.net"
  tls_pubkey_pinset:
  - digest: "sha256"
    value: 0x7e8c59467221f606695a797ecc488a6b4109dab7421aba0c5a6d3681ac5273d4
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
listen_addresses:
- 127.0.0.1
- 0::1
